POST https://urlie.herokuapp.com/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://github.com/dsckiet/url-shortner-backend",
    "customCode": "url",
    "title": "GIthub Repo. link"
}